### ISSUE TITLE
[FR] Add total mentions per chapter

### ISSUE THREAD

**Issue by njncalub** [wandering-inndex/seed-data#6]
## Description

For each `[Bracket Content]`, add how many times it was mentioned in a chapter, and how many times in total it was mentioned in the selected range.

![chrome_r8ITT8pldu](https://user-images.githubusercontent.com/1902957/205620763-df1cb008-f231-40b8-ae7f-168fff491c6d.png)

## Motivation

It will be better for statistical purposes.

## Suggested Implementation

Update the chapter parser to tally the contents, then add it to the yaml file.

Currently, we can add the total to the text itself. Just add an unused token as a separator. For example `<text>|<count>`:

```yaml
- id: "twiwnch0002011"
  mentions:
    - "[Innkeeper Class Obtained!]|1"
- id: "twiwnch0003026"
  mentions:
    - "[Gambler]|10"
```

On our neo4j updater, parse the count and put it as a property in the `MENTIONED_IN` relationship.

## Alternate Implementations

N/A
